name: Deploy to EC2

on:
  push:
    branches:
      - "main"

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Create ZIP Archive
        run: |
          zip -r branch-files.zip .

      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: branch-files
          path: branch-files.zip

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    if: ${{ always() }}
    steps:
      - name: Download Lambda branch-files.zip
        uses: actions/download-artifact@v4
        with:
          name: branch-files

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      
      - name: Install AWS CLI v2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version
      
      - name: Upload to S3
        run: aws s3 cp branch-files.zip s3://aws-master-lab5/branch-files.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy artifact to EC2
        run: |
          scp branch-files.zip ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/

      - name: Install unzip on EC2
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "sudo yum update && sudo yum install -y unzip"

      - name: Extract artifact on EC2
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "unzip /home/ubuntu/branch-files.zip -d /home/ubuntu/branch-files"

      - name: Run Bash Script to Deploy App
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "chmod +x /home/ubuntu/branch-files/deploy.sh && /home/ubuntu/branch-files/deploy.sh"
